### ISSUE TITLE
[BUG] Markdown rendering is not disabled by `no_color=True`

### ISSUE THREAD

**Issue by ofek** [Textualize/rich#2585] opened 2022-10-16 21:35 UTC
**Describe the bug**

The following renders Markdown when one would expect otherwise:

```python
from rich.console import Console
from rich.markdown import Markdown

console = Console(no_color=True)
console.print(Markdown(text))
```

**Platform**
<details>
<summary>Click to expand</summary>

```
╭───────────────────────── <class 'rich.console.Console'> ─────────────────────────╮
│ A high level console interface.                                                  │
│                                                                                  │
│ ╭──────────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=199 ColorSystem.TRUECOLOR>                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                  │
│     color_system = 'truecolor'                                                   │
│         encoding = 'utf-8'                                                       │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> │
│           height = 41                                                            │
│    is_alt_screen = False                                                         │
│ is_dumb_terminal = False                                                         │
│   is_interactive = True                                                          │
│       is_jupyter = False                                                         │
│      is_terminal = True                                                          │
│   legacy_windows = False                                                         │
│         no_color = False                                                         │
│          options = ConsoleOptions(                                               │
│                        size=ConsoleDimensions(width=199, height=41),             │
│                        legacy_windows=False,                                     │
│                        min_width=1,                                              │
│                        max_width=199,                                            │
│                        is_terminal=True,                                         │
│                        encoding='utf-8',                                         │
│                        max_height=41,                                            │
│                        justify=None,                                             │
│                        overflow=None,                                            │
│                        no_wrap=False,                                            │
│                        highlight=None,                                           │
│                        markup=None,                                              │
│                        height=None                                               │
│                    )                                                             │
│            quiet = False                                                         │
│           record = False                                                         │
│         safe_box = True                                                          │
│             size = ConsoleDimensions(width=199, height=41)                       │
│        soft_wrap = False                                                         │
│           stderr = False                                                         │
│            style = None                                                          │
│         tab_size = 8                                                             │
│            width = 199                                                           │
╰──────────────────────────────────────────────────────────────────────────────────╯
╭── <class 'rich._windows.WindowsConsoleFeatures'> ───╮
│ Windows features available.                         │
│                                                     │
│ ╭─────────────────────────────────────────────────╮ │
│ │ WindowsConsoleFeatures(vt=True, truecolor=True) │ │
│ ╰─────────────────────────────────────────────────╯ │
│                                                     │
│ truecolor = True                                    │
│        vt = True                                    │
╰─────────────────────────────────────────────────────╯
╭────── Environment Variables ───────╮
│ {                                  │
│     'TERM': None,                  │
│     'COLORTERM': None,             │
│     'CLICOLOR': None,              │
│     'NO_COLOR': None,              │
│     'TERM_PROGRAM': None,          │
│     'COLUMNS': None,               │
│     'LINES': None,                 │
│     'JUPYTER_COLUMNS': None,       │
│     'JUPYTER_LINES': None,         │
│     'JPY_PARENT_PID': None,        │
│     'VSCODE_VERBOSE_LOGGING': None │
│ }                                  │
╰────────────────────────────────────╯
platform="Windows"
```
</details>

**Comment by willmcgugan** [comment] 2022-10-16 21:44
Why would you expect no_color to not render Markdown?

**Comment by ofek** [comment] 2022-10-16 22:09
I would expect that to indicate "this may be a tty, but please no ANSI codes" which ppl often control with https://no-color.org

**Comment by davep** [comment] 2022-10-17 07:59
@ofek Is your query about it rendering markdown at all, or that, for example, `**bold**` text will still appear bold? Is the query perhaps nothing to do with markdown at all? For example, this code:

```python
from rich.console import Console

console = Console(no_color=True)
console.print( "[bold][red]This is bold red[/][/]")
```

will, as `no_color` would imply, *not* render the text in red, but does still render it bold.

Were you expecting to see something more like you'd get if you set `color_system` to `None`:

```python
from rich.console import Console

console = Console(color_system=None)
console.print( "[bold][red]This is bold red[/][/]")
```

where neither the red nor the bold get rendered?

**Comment by willmcgugan** [comment] 2022-10-17 08:35
@ofek You may be expecting `no_color` to remove all ansi escape sequences. However, it is only intended to remove *color*, so bold, italic etc will remain. The author of no-color.org has confirmed this is the desired behaviour.

**Comment by ofek** [comment] 2022-10-17 13:41
I guess I'm looking for a way for a user to define an env var that disables everything which I can then translate to Console options:

```python
console = Console(color_system=None, no_color=True, markup=False, emoji=False, highlight=False)
```

**Comment by willmcgugan** [comment] 2022-10-17 13:58
You can already set `TERM=dumb` to remove all escape sequences. Is that what you are looking for?

**Comment by willmcgugan** [comment] 2022-10-17 15:24
Yep. `quiet=True` on the `Console` constructor.

**Comment by willmcgugan** [comment] 2024-08-26 14:28
Closing for now. Feel free to re-open if you have more informaiton.

**Closed by willmcgugan** 2024-08-26 14:28 UTC
Labels: Needs triage
