### ISSUE TITLE
[BUG] rich.console.Console.print might hang for unknown reason under weird conditions

### ISSUE THREAD

**Issue by christiandreher** [Textualize/rich#2716] opened 2022-12-23 20:08 UTC
- [x] I've checked [docs](https://rich.readthedocs.io/en/latest/introduction.html) and [closed issues](https://github.com/Textualize/rich/issues?q=is%3Aissue+is%3Aclosed) for possible solutions.
- [x] I can't find my issue in the [FAQ](https://github.com/Textualize/rich/blob/master/FAQ.md).

First of all, **thanks for all your work**, it is very much appreciated. I love working with Rich. However, I now faced a really arcane bug which I have been debugging the whole week, full time. I now managed to create an MWE where the problem is 100% reproducible (under weird conditions) on my PC so I wanted to share it here.

**Describe the bug**

I found that given certain outputs, calling `print` on `rich.console.Console` will result in the `print` call hanging, and not returning.

I am running an application where other processes produce lots of outputs. These outputs are captured and printed again using Rich. Some specific strings will make this problem occur. Using plain standard Python `print` instead of `rich.console.Console.print` solves this issue for me, but I am uncomfortable with it since it's a workaround in my book...

**The MWE - Script**

With this MWE, the problem of `print` hanging is reproducible 100% of the time for me. However, weird conditions apply:

1. My terminal must be full-screen. It will not hang in windowed mode.
2. The string to be printed must not change. Minimal changes will make it not hang again. There are some letters which can be removed though, for example, "file:" can be replaced with "fil:" and it will still hang, but not "fle:" or so...

```python
#!/usr/bin/env python

from rich.console import Console

c = Console()

kwargs = {
    "crop": False,
    "no_wrap": True,
    "markup": False,
    "highlight": False,
}

c.print("Might hang now:")
c.print(b"\x1b[0m        Adding custom aron generation target for file: /home/chris/code/armarde/armarx/RobotSkillTemplates/source/RobotSkillTemplates/libraries/skill_joint_control/aron/MoveJointsWithVelocityAcceptedType.xml\x1b[0m".decode("utf-8"), **kwargs)
c.print("Didn't hang!")
```

**The MWE - Environment:**

I created the environment as such:

```shell
 chris@i61nb083  ~/tmp  mkdir mwe_rich
 chris@i61nb083  ~/tmp  cd mwe_rich 
 chris@i61nb083  ~/tmp/mwe_rich  python3 -m venv .venv
 chris@i61nb083  ~/tmp/mwe_rich  source .venv/bin/activate

 (.venv)  chris@i61nb083  ~/tmp/mwe_rich  pip install rich==10.9.0
Collecting rich==10.9.0
  Using cached https://files.pythonhosted.org/packages/e9/c4/ea9a6e34dd5c4c3049b0a86c49feb7f38c9f5e901ffb6eeb832e89dfa540/rich-10.9.0-py3-none-any.whl
Collecting commonmark<0.10.0,>=0.9.0 (from rich==10.9.0)
  Using cached https://files.pythonhosted.org/packages/b1/92/dfd892312d822f36c55366118b95d914e5f16de11044a27cf10a7d71bbbf/commonmark-0.9.1-py2.py3-none-any.whl
Collecting pygments<3.0.0,>=2.6.0 (from rich==10.9.0)
  Using cached https://files.pythonhosted.org/packages/4f/82/672cd382e5b39ab1cd422a672382f08a1fb3d08d9e0c0f3707f33a52063b/Pygments-2.13.0-py3-none-any.whl
Collecting colorama<0.5.0,>=0.4.0 (from rich==10.9.0)
  Using cached https://files.pythonhosted.org/packages/77/8b/7550e87b2d308a1b711725dfaddc19c695f8c5fa413c640b2be01662f4e6/colorama-0.4.5-py2.py3-none-any.whl
Collecting dataclasses<0.9,>=0.7; python_version >= "3.6" and python_version < "3.7" (from rich==10.9.0)
  Using cached https://files.pythonhosted.org/packages/fe/ca/75fac5856ab5cfa51bbbcefa250182e50441074fdc3f803f6e76451fab43/dataclasses-0.8-py3-none-any.whl
Collecting typing-extensions<4.0.0,>=3.7.4; python_version < "3.8" (from rich==10.9.0)
  Using cached https://files.pythonhosted.org/packages/74/60/18783336cc7fcdd95dae91d73477830aa53f5d3181ae4fe20491d7fc3199/typing_extensions-3.10.0.2-py3-none-any.whl
Installing collected packages: commonmark, pygments, colorama, dataclasses, typing-extensions, rich
Successfully installed colorama-0.4.5 commonmark-0.9.1 dataclasses-0.8 pygments-2.13.0 rich-10.9.0 typing-extensions-3.10.0.2
```

Please note: I know that the version of Rich is rather old, but also for up-to-date Rich this problem appears. The only thing that changes are the strings needed to make `print` hang. It was really cumbersome to produce this MWE, so I hope you bear with me...

**The MWE - Execution/Result:**

Executing the script (called `some_process`) will then just hang:

![image](https://user-images.githubusercontent.com/40353855/209399935-003597ce-aa4c-4e7e-996a-8ed96712ce90.png)

**The MWE - Stachtrace on SIGINT:**

If I SIGINT (<kbd>Ctrl</kbd>+<kbd>C</kbd>) the process, I get the following stack trace:

```shell
 (.venv)  chris@i61nb083  ~/tmp/mwe_rich  ./some_process          
Might hang now:
^CTraceback (most recent call last):
  File "./some_process", line 15, in <module>
    c.print(b"\x1b[0m        Adding custom aron generation target for file: /home/chris/code/armarde/armarx/RobotSkillTemplates/source/RobotSkillTemplates/libraries/skill_joint_control/aron/MoveJointsWithVelocityAcceptedType.xml\x1b[0m".decode("utf-8"), **kwargs)
  File "/home/chris/tmp/mwe_rich/.venv/lib/python3.6/site-packages/rich/console.py", line 1594, in print
    extend(render(renderable, render_options))
  File "/home/chris/tmp/mwe_rich/.venv/lib/python3.6/site-packages/rich/console.py", line 1225, in render
    for render_output in iter_render:
  File "/home/chris/tmp/mwe_rich/.venv/lib/python3.6/site-packages/rich/text.py", line 574, in __rich_console__
    no_wrap=pick_bool(self.no_wrap, options.no_wrap, False),
  File "/home/chris/tmp/mwe_rich/.venv/lib/python3.6/site-packages/rich/text.py", line 1091, in wrap
    line.truncate(width, overflow=wrap_overflow)
  File "/home/chris/tmp/mwe_rich/.venv/lib/python3.6/site-packages/rich/text.py", line 744, in truncate
    self.plain = set_cell_size(self.plain, max_width)
  File "/home/chris/tmp/mwe_rich/.venv/lib/python3.6/site-packages/rich/cells.py", line 90, in set_cell_size
    before_len = cell_len(before)
  File "/home/chris/tmp/mwe_rich/.venv/lib/python3.6/site-packages/rich/cells.py", line 22, in cell_len
    total_size = sum(_get_size(character) for character in text)
  File "/home/chris/tmp/mwe_rich/.venv/lib/python3.6/site-packages/rich/cells.py", line 22, in <genexpr>
    total_size = sum(_get_size(character) for character in text)
KeyboardInterrupt
```

**Platform**
<details>
<summary>Click to expand</summary>

**Platform Info**

```shell
 chris@i61nb083  ~  lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
 chris@i61nb083  ~  uname -a
Linux i61nb083 5.4.0-126-generic #142~18.04.1-Ubuntu SMP Thu Sep 1 16:25:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
 chris@i61nb083  ~  python --version
Python 3.6.9
```

**Output of `python -m rich.diagnose`**

```shell
 (.venv)  chris@i61nb083  ~/tmp/mwe_rich  python -m rich.diagnose
╭───────────────────────── <class 'rich.console.Console'> ─────────────────────────╮
│ A high level console interface.                                                  │
│                                                                                  │
│ ╭──────────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=211 ColorSystem.TRUECOLOR>                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                  │
│     color_system = 'truecolor'                                                   │
│         encoding = 'utf-8'                                                       │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'> │
│           height = 54                                                            │
│    is_alt_screen = False                                                         │
│ is_dumb_terminal = False                                                         │
│   is_interactive = True                                                          │
│       is_jupyter = False                                                         │
│      is_terminal = True                                                          │
│   legacy_windows = False                                                         │
│         no_color = False                                                         │
│          options = ConsoleOptions(                                               │
│                        size=ConsoleDimensions(width=211, height=54),             │
│                        legacy_windows=False,                                     │
│                        min_width=1,                                              │
│                        max_width=211,                                            │
│                        is_terminal=True,                                         │
│                        encoding='utf-8',                                         │
│                        max_height=54,                                            │
│                        justify=None,                                             │
│                        overflow=None,                                            │
│                        no_wrap=False,                                            │
│                        highlight=None,                                           │
│                        markup=None,                                              │
│                        height=None                                               │
│                    )                                                             │
│            quiet = False                                                         │
│           record = False                                                         │
│         safe_box = True                                                          │
│             size = ConsoleDimensions(width=211, height=54)                       │
│        soft_wrap = False                                                         │
│           stderr = False                                                         │
│            style = None                                                          │
│         tab_size = 8                                                             │
│            width = 211                                                           │
╰──────────────────────────────────────────────────────────────────────────────────╯
```

**Output of `pip freeze | grep rich`**

```shell
 (.venv)  chris@i61nb083  ~/tmp/mwe_rich  pip freeze | grep rich
rich==10.9.0
```

</details>

Please let me know of anything I can do to help you track down this issue. I can also open a Zoom call and show the problem live.

Happy holidays!

**Comment by willmcgugan** [comment] 2022-12-23 20:37
This was fixed in v10.14.0 with https://github.com/Textualize/rich/pull/1683

I can't reproduce it after that version.

**Comment by christiandreher** [comment] 2022-12-23 20:40
> This was fixed in v10.14.0 with #1683
> 
> I can't reproduce it after that version.

Thanks for the info, I wasn't fully aware! I will then try to reproduce it on newest Rich.

**Comment by willmcgugan** [comment] 2022-12-24 10:36
Assuming fixed. Reopen if you can reproduce with the latest Rich.

**Closed** 2022-12-24 10:42 UTC
Labels: Needs triage

**Comment by christiandreher** [comment] 2022-12-29 15:37
> Assuming fixed. Reopen if you can reproduce with the latest Rich.

Yes it is fixed, it was indeed just the version. Somehow I must have made an error when I tried it with 12.6.0. But thanks for your help!
