### ISSUE TITLE
[BUG] inconsistent coloring of complex numbers

### ISSUE THREAD

**Issue by flaport** [Textualize/rich#2214] opened 2022-04-22 11:27 UTC
Not sure if I should report this as a bug or as a feature request, but there is a very minor issue when printing complex numbers: the decimal part of the imaginary number is uncolored.

try for example:

```python
>>> from rich import pretty
>>> pretty.install()
>>> 3.05 + 2.06j
(3.05+2.06j)
```

![image](https://user-images.githubusercontent.com/15832886/164705103-eca06cf1-a1c3-41ed-973c-0a02d70c8249.png)

I tried this on Linux, rich version 12.2.0. This "bug" appears both in the terminal (alacritty in my case) as well as in jupyter notebooks, which makes me believe it is platform independent.

**Comment by willmcgugan** [comment] 2022-04-22 14:09
Rich doesn't have any explicit supports for complex numbers. If you're adept with regexes, you could add it to highlighter.py

**Comment by flaport** [comment] 2022-04-22 15:40
Thanks will, I'll try that.

However, respectfully, complex numbers are natively supported by python so in my opinion they should also be natively supported by the rich pretty printer. Having to specify the same regex over and over in interactive sessions (which many scientific exploratory notebooks are for example) is not really user friendly...

Like I said, it's a very minor issue and I understand that adding this feature might yield unnecessary overhead on your side. If that's the case just disregard it, but I think as rich will become more popular in the scientific community you might get this question again.

**Comment by willmcgugan** [comment] 2022-04-22 17:47
I was actually suggesting that you could contribute this to highlighter.py in the repo, if you could come up with the regex. I'm happy to add it.

**Comment by flaport** [comment] 2022-04-22 17:55
Sure! I'll give it a shot 🙂

**Comment by DrBenton** [comment] 2022-04-25 12:56
Hi @flaport ! :slightly_smiling_face:  
Just a quick message to let you know that the issue is fixed now, and should be merged soon. Thank you for your report! :-) 
> #2219

**Comment by flaport** [comment] 2022-04-25 14:14
Ai, lost my opportunity to contribute to this awesome library 😉. Thanks a lot for this quick resolution!

**Closed** 2022-04-26 10:35 UTC
Labels: accepted
