### ISSUE TITLE
[BUG] 12.3.0: pyets if ailing in `tests/test_traceback.py::test_guess_lexer_yaml_j2` unit

### ISSUE THREAD

**Issue by kloczek** [Textualize/rich#2230] opened 2022-04-26 19:17 UTC
I'm trying to package your module as an rpm package. So I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account.
- `python3 -sBm build -w --no-isolation`
- because I'm calling `build` with `--no-isolation` I'm using during all processes only locally installed modules
- install .whl file in </install/prefix>
- run pytest with PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>

Prev version was OK.
Here is pytest output:
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-rich-12.3.0-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-rich-12.3.0-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.13, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/rich-12.3.0
collected 670 items

tests/test_align.py ................                                                                                                                                 [  2%]
tests/test_ansi.py ..                                                                                                                                                [  2%]
tests/test_bar.py .......                                                                                                                                            [  3%]
tests/test_block_bar.py ....                                                                                                                                         [  4%]
tests/test_box.py ......                                                                                                                                             [  5%]
tests/test_card.py .                                                                                                                                                 [  5%]
tests/test_cells.py ..                                                                                                                                               [  5%]
tests/test_color.py .................                                                                                                                                [  8%]
tests/test_color_triplet.py ...                                                                                                                                      [  8%]
tests/test_columns.py .                                                                                                                                              [  8%]
tests/test_columns_align.py .                                                                                                                                        [  8%]
tests/test_console.py ......................................................................................                                                         [ 21%]
tests/test_constrain.py .                                                                                                                                            [ 21%]
tests/test_containers.py ....                                                                                                                                        [ 22%]
tests/test_control.py ......                                                                                                                                         [ 23%]
tests/test_emoji.py ......                                                                                                                                           [ 24%]
tests/test_file_proxy.py ...                                                                                                                                         [ 24%]
tests/test_filesize.py ..                                                                                                                                            [ 25%]
tests/test_highlighter.py ..................................................                                                                                         [ 32%]
tests/test_inspect.py ......s...                                                                                                                                     [ 34%]
tests/test_json.py .                                                                                                                                                 [ 34%]
tests/test_jupyter.py .                                                                                                                                              [ 34%]
tests/test_layout.py ......                                                                                                                                          [ 35%]
tests/test_live.py ..........                                                                                                                                        [ 36%]
tests/test_live_render.py ....                                                                                                                                       [ 37%]
tests/test_log.py ...                                                                                                                                                [ 37%]
tests/test_logging.py ....                                                                                                                                           [ 38%]
tests/test_lrucache.py .                                                                                                                                             [ 38%]
tests/test_markdown.py ..                                                                                                                                            [ 38%]
tests/test_markdown_no_hyperlinks.py .                                                                                                                               [ 38%]
tests/test_markup.py ....................                                                                                                                            [ 41%]
tests/test_measure.py ....                                                                                                                                           [ 42%]
tests/test_padding.py .....                                                                                                                                          [ 43%]
tests/test_palette.py .                                                                                                                                              [ 43%]
tests/test_panel.py ..........                                                                                                                                       [ 44%]
tests/test_pick.py .                                                                                                                                                 [ 45%]
tests/test_pretty.py .....................................s...                                                                                                       [ 51%]
tests/test_progress.py ......................................                                                                                                        [ 56%]
tests/test_prompt.py ......                                                                                                                                          [ 57%]
tests/test_protocol.py ......                                                                                                                                        [ 58%]
tests/test_ratio.py .......                                                                                                                                          [ 59%]
tests/test_repr.py ........                                                                                                                                          [ 60%]
tests/test_rich_print.py .......                                                                                                                                     [ 61%]
tests/test_rule.py .......                                                                                                                                           [ 62%]
tests/test_screen.py .                                                                                                                                               [ 63%]
tests/test_segment.py ................................................                                                                                               [ 70%]
tests/test_spinner.py .....                                                                                                                                          [ 71%]
tests/test_stack.py .                                                                                                                                                [ 71%]
tests/test_status.py ..                                                                                                                                              [ 71%]
tests/test_style.py .........................                                                                                                                        [ 75%]
tests/test_styled.py .                                                                                                                                               [ 75%]
tests/test_syntax.py ....................                                                                                                                            [ 78%]
tests/test_table.py ........                                                                                                                                         [ 79%]
tests/test_text.py ...................................................................................                                                               [ 91%]
tests/test_theme.py .....                                                                                                                                            [ 92%]
tests/test_tools.py ....                                                                                                                                             [ 93%]
tests/test_traceback.py ..............F....                                                                                                                          [ 96%]
tests/test_tree.py .....s.s.                                                                                                                                         [ 97%]
tests/test_windows_renderer.py sssssssssssssssss                                                                                                                     [100%]

================================================================================= FAILURES =================================================================================
_________________________________________________________________________ test_guess_lexer_yaml_j2 _________________________________________________________________________

    def test_guess_lexer_yaml_j2():
        # https://github.com/Textualize/rich/issues/2018
        code = """\
    foobar:
        something: {{ raiser() }}
        else: {{ 5 + 5 }}
        """
>       assert Traceback._guess_lexer("test.yaml.j2", code) == "text"
E       AssertionError: assert 'YAML+Jinja' == 'text'
E         - text
E         + YAML+Jinja

tests/test_traceback.py:280: AssertionError
============================================================================= warnings summary =============================================================================
tests/test_markup.py:147
  /home/tkloczko/rpmbuild/BUILD/rich-12.3.0/tests/test_markup.py:147: DeprecationWarning: invalid escape sequence \[
    result = str(render("[dim white]\[url=[/]"))

tests/test_traceback.py:52
  /home/tkloczko/rpmbuild/BUILD/rich-12.3.0/tests/test_traceback.py:52: DeprecationWarning: invalid escape sequence \.
    "^│ .+rich/tests/test_traceback\.py:",

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================================================================= short test summary info ==========================================================================
SKIPPED [1] tests/test_inspect.py:205: rendered differently on py3.8
SKIPPED [1] tests/test_pretty.py:492: rendered differently on py3.8
SKIPPED [1] tests/test_tree.py:81: Windows specific
SKIPPED [1] tests/test_tree.py:121: Windows specific
SKIPPED [1] tests/test_windows_renderer.py:23: windows only
SKIPPED [1] tests/test_windows_renderer.py:31: windows only
SKIPPED [1] tests/test_windows_renderer.py:41: windows only
SKIPPED [1] tests/test_windows_renderer.py:51: windows only
SKIPPED [1] tests/test_windows_renderer.py:61: windows only
SKIPPED [1] tests/test_windows_renderer.py:69: windows only
SKIPPED [4] tests/test_windows_renderer.py:77: windows only
SKIPPED [3] tests/test_windows_renderer.py:96: windows only
SKIPPED [1] tests/test_windows_renderer.py:112: windows only
SKIPPED [1] tests/test_windows_renderer.py:120: windows only
SKIPPED [1] tests/test_windows_renderer.py:128: windows only
SKIPPED [1] tests/test_windows_renderer.py:136: windows only
FAILED tests/test_traceback.py::test_guess_lexer_yaml_j2 - AssertionError: assert 'YAML+Jinja' == 'text'
========================================================== 1 failed, 648 passed, 21 skipped, 2 warnings in 6.01s ===========================================================
```

**Comment by mgorny** [comment] 2022-04-26 20:41
I'm guessing this is caused by pygments/pygments#2100 in Pygments 2.12.0. I suppose the purpose of the test is to verify the behavior against unrecognized filename, so perhaps something that looks more like junk should be used there.

**Comment by kloczek** [comment] 2022-04-26 21:16
I've started reporting few days ago that kind of issues as I've switched  from use sphinx<>setuptools to raw sphinx-build command on building my rpm pacjkages.
Few modules maintainers already figured out what needs to be fixed.
If you want some examples I can drop you few URLS to some already integrated commits.

**Comment by kloczek** [comment] 2022-04-26 21:18
(sorry deleted prev comment .. wrong window)
I can confitm I'm using pygments 2.12.0.

**Comment by willmcgugan** [comment] 2022-05-03 10:49
Should be fixed in master.

**Closed by willmcgugan** 2022-05-03 10:49 UTC
Labels: Needs triage

**Comment by kloczek** [comment] 2022-05-03 11:05
Tested e2332480 and it works now.
Thx 👍 
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-rich-12.3.0-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-rich-12.3.0-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.13, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/rich-12.3.0
collected 670 items

tests/test_align.py ................                                                                                                                                 [  2%]
tests/test_ansi.py ..                                                                                                                                                [  2%]
tests/test_bar.py .......                                                                                                                                            [  3%]
tests/test_block_bar.py ....                                                                                                                                         [  4%]
tests/test_box.py ......                                                                                                                                             [  5%]
tests/test_card.py .                                                                                                                                                 [  5%]
tests/test_cells.py ..                                                                                                                                               [  5%]
tests/test_color.py .................                                                                                                                                [  8%]
tests/test_color_triplet.py ...                                                                                                                                      [  8%]
tests/test_columns.py .                                                                                                                                              [  8%]
tests/test_columns_align.py .                                                                                                                                        [  8%]
tests/test_console.py ......................................................................................                                                         [ 21%]
tests/test_constrain.py .                                                                                                                                            [ 21%]
tests/test_containers.py ....                                                                                                                                        [ 22%]
tests/test_control.py ......                                                                                                                                         [ 23%]
tests/test_emoji.py ......                                                                                                                                           [ 24%]
tests/test_file_proxy.py ...                                                                                                                                         [ 24%]
tests/test_filesize.py ..                                                                                                                                            [ 25%]
tests/test_highlighter.py ..................................................                                                                                         [ 32%]
tests/test_inspect.py ......s...                                                                                                                                     [ 34%]
tests/test_json.py .                                                                                                                                                 [ 34%]
tests/test_jupyter.py .                                                                                                                                              [ 34%]
tests/test_layout.py ......                                                                                                                                          [ 35%]
tests/test_live.py ..........                                                                                                                                        [ 36%]
tests/test_live_render.py ....                                                                                                                                       [ 37%]
tests/test_log.py ...                                                                                                                                                [ 37%]
tests/test_logging.py ....                                                                                                                                           [ 38%]
tests/test_lrucache.py .                                                                                                                                             [ 38%]
tests/test_markdown.py ..                                                                                                                                            [ 38%]
tests/test_markdown_no_hyperlinks.py .                                                                                                                               [ 38%]
tests/test_markup.py ....................                                                                                                                            [ 41%]
tests/test_measure.py ....                                                                                                                                           [ 42%]
tests/test_padding.py .....                                                                                                                                          [ 43%]
tests/test_palette.py .                                                                                                                                              [ 43%]
tests/test_panel.py ..........                                                                                                                                       [ 44%]
tests/test_pick.py .                                                                                                                                                 [ 45%]
tests/test_pretty.py .....................................s...                                                                                                       [ 51%]
tests/test_progress.py ......................................                                                                                                        [ 56%]
tests/test_prompt.py ......                                                                                                                                          [ 57%]
tests/test_protocol.py ......                                                                                                                                        [ 58%]
tests/test_ratio.py .......                                                                                                                                          [ 59%]
tests/test_repr.py ........                                                                                                                                          [ 60%]
tests/test_rich_print.py .......                                                                                                                                     [ 61%]
tests/test_rule.py .......                                                                                                                                           [ 62%]
tests/test_screen.py .                                                                                                                                               [ 63%]
tests/test_segment.py ................................................                                                                                               [ 70%]
tests/test_spinner.py .....                                                                                                                                          [ 71%]
tests/test_stack.py .                                                                                                                                                [ 71%]
tests/test_status.py ..                                                                                                                                              [ 71%]
tests/test_style.py .........................                                                                                                                        [ 75%]
tests/test_styled.py .                                                                                                                                               [ 75%]
tests/test_syntax.py ....................                                                                                                                            [ 78%]
tests/test_table.py ........                                                                                                                                         [ 79%]
tests/test_text.py ...................................................................................                                                               [ 91%]
tests/test_theme.py .....                                                                                                                                            [ 92%]
tests/test_tools.py ....                                                                                                                                             [ 93%]
tests/test_traceback.py ...................                                                                                                                          [ 96%]
tests/test_tree.py .....s.s.                                                                                                                                         [ 97%]
tests/test_windows_renderer.py sssssssssssssssss                                                                                                                     [100%]

============================================================================= warnings summary =============================================================================
tests/test_markup.py:147
  /home/tkloczko/rpmbuild/BUILD/rich-12.3.0/tests/test_markup.py:147: DeprecationWarning: invalid escape sequence \[
    result = str(render("[dim white]\[url=[/]"))

tests/test_traceback.py:52
  /home/tkloczko/rpmbuild/BUILD/rich-12.3.0/tests/test_traceback.py:52: DeprecationWarning: invalid escape sequence \.
    "^│ .+rich/tests/test_traceback\.py:",

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================================================================= short test summary info ==========================================================================
SKIPPED [1] tests/test_inspect.py:205: rendered differently on py3.8
SKIPPED [1] tests/test_pretty.py:492: rendered differently on py3.8
SKIPPED [1] tests/test_tree.py:81: Windows specific
SKIPPED [1] tests/test_tree.py:121: Windows specific
SKIPPED [1] tests/test_windows_renderer.py:23: windows only
SKIPPED [1] tests/test_windows_renderer.py:31: windows only
SKIPPED [1] tests/test_windows_renderer.py:41: windows only
SKIPPED [1] tests/test_windows_renderer.py:51: windows only
SKIPPED [1] tests/test_windows_renderer.py:61: windows only
SKIPPED [1] tests/test_windows_renderer.py:69: windows only
SKIPPED [4] tests/test_windows_renderer.py:77: windows only
SKIPPED [3] tests/test_windows_renderer.py:96: windows only
SKIPPED [1] tests/test_windows_renderer.py:112: windows only
SKIPPED [1] tests/test_windows_renderer.py:120: windows only
SKIPPED [1] tests/test_windows_renderer.py:128: windows only
SKIPPED [1] tests/test_windows_renderer.py:136: windows only
=============================================================== 649 passed, 21 skipped, 2 warnings in 5.64s ================================================================
```
