### ISSUE TITLE
[REQUEST] Progress for generators with unknown length

### ISSUE THREAD

**Issue by SeanNaren** [Textualize/rich#1528] opened 2021-09-28 09:26 UTC
Related https://github.com/willmcgugan/rich/issues/1022

Hey @willmcgugan!

We're trying to make Rich the main progress bar in PyTorch Lightning, superseding TQDM: https://github.com/PyTorchLightning/pytorch-lightning/pull/9647

However we noticed that generators are not supported for the progress object, which means IterableDatasets cannot be supported (a common use case for PyTorch). Do you have any suggestions on something that could replace this and give atleast some iteration progress or know if support for generators is possible?

**Comment by willmcgugan** [comment] 2021-09-28 10:52
Generators absolutely are supported by Progress.

However, there is no way to get the total number of steps from a generator. Without it, theres no way to calculate total progress, time remaining etc. In this case you would need to specify the `total` manually.

So what would you want Rich to do when total is not available?

**Comment by SeanNaren** [comment] 2021-09-28 11:27
thanks @willmcgugan! appreciate you and this awesome library ❤️  

we came up with a solution, but maybe you have ideas to deal with my hacky lil solution :) the goal is to support an unknown total, as it cannot be defined

Currently it looks like this now:
![demo](https://user-images.githubusercontent.com/6707363/135078029-1e12d95b-a44b-476f-a788-c91b2dbf7b73.gif)

It involved overriding a few methods of a couple of components to support `total=float('inf')` as an input. These can be seen here:

https://github.com/PyTorchLightning/pytorch-lightning/pull/9647/files#diff-1ed8aa90c90b04a74eeb942b0ad5483dff76b05a7de68787495dddbc6aaa40c0R29-R93

Overall it seems to work great, but I wonder if you have any feedback!

**Comment by jnoortheen** [comment] 2022-01-12 01:42
> So what would you want Rich to do when total is not available?

`rich` can follow the `tqdm`'s approach. When total is not available, it can show the number of tasks executed along with the time it spent, but hiding progress bar and remaining time.

**Comment by willmcgugan** [comment] 2022-02-11 11:38
Dupe of #1054

**Closed by willmcgugan** 2022-02-11 11:38 UTC
Labels: Needs triage
