### ISSUE TITLE
[BUG] Misaligned box boundaries in SVG generated from a rich-click help dialogue

### ISSUE THREAD

**Issue by apcamargo** [Textualize/rich#2279] opened 2022-05-16 17:06 UTC
I'm using the new `save_svg` method to write a SVG of a help dialogue generated with @ewels' `rich-click`. However, the `│` characters of the right side of the box are misaligned.

![HELP](https://user-images.githubusercontent.com/22940964/168649747-8a492f48-3b70-4b83-860c-1906e8db7502.svg)

Apparently these additional whitespaces are being caused my markup. For example, the `DESTINATION` in the dialogue is `[u]DESTINATION[/u]`. But this seems to be another issue, since it doesn't happen when I keep the default Fira Code font.

```
Python 3.8.12
rich 12.4.1
macOS 12.3.1
```

**Comment by willmcgugan** [comment] 2022-05-16 18:16
I don’t see any misalignment here. You say you don’t see it when you keep the default font. Does that mean you are modifying the font in the SVG?

**Comment by willmcgugan** [comment] 2022-05-16 18:22
It will be a font issue. The font should be monospaced, but clearly isn’t.

**Comment by apcamargo** [comment] 2022-05-16 18:24
I'm using the default settings in the screenshot, with Fira Code. Also, Safari rendered my previous screenshot (with Cascadia Mono) perfectly:

![image](https://user-images.githubusercontent.com/22940964/168657934-50256099-3ad7-44e4-b09e-bf9f0de9a709.png)

It looks like it's a compatibility issue with Firefox

**Comment by apcamargo** [comment] 2022-05-16 18:52
Here's the same webpage in Safari and Firefox:

![image](https://user-images.githubusercontent.com/22940964/168662224-86b9cd4d-ade4-4e7b-984a-e0c7330f851f.png)

![image](https://user-images.githubusercontent.com/22940964/168662303-fa5eea4a-e911-4fed-a43b-c2fc17c41a82.png)

**Comment by willmcgugan** [comment] 2022-05-16 18:55
Got her best results if you embed the SVGs and include the font CSS from the Rich docs, but I’m afraid there is nothing I can do about browser issues.

**Comment by apcamargo** [comment] 2022-05-16 18:57
The issue persists with the CSS. But yeah, there's nothing that can be done about that. Maybe a warning that SVGs might not render perfectly in Firefox?

**Comment by willmcgugan** [comment] 2022-05-16 18:59
Are you embedding the SVGs or using an img tag?

**Comment by apcamargo** [comment] 2022-05-16 19:07
Tried both

**Comment by ewels** [comment] 2022-05-16 21:30
@apcamargo - off topic, but I'm curious how you're getting the coloured help text output.. Do you have the code anywhere? 

I'm vaguely playing with similar ideas but most things I've tried so far result in rich stripping the colour due to piping output / otherwise not being a proper terminal.

**Comment by apcamargo** [comment] 2022-05-16 21:37
Very dirty code:

```python
def _get_rich_console() -> Console:
    console = Console(
        record=True, # <- I added this parameter
        theme=Theme(
            {
                "option": STYLE_OPTION,
                "switch": STYLE_SWITCH,
                "metavar": STYLE_METAVAR,
                "metavar_sep": STYLE_METAVAR_SEPARATOR,
                "usage": STYLE_USAGE,
            }
        ),
        highlighter=highlighter,
        color_system=COLOR_SYSTEM,
    )

…

    # Epilogue if we have it
    if obj.epilog:
        # Remove single linebreaks, replace double with single
        lines = obj.epilog.split("\n\n")
        epilogue = "\n".join([x.replace("\n", " ").strip() for x in lines])
        console.print(Padding(Align(highlighter(epilogue), width=MAX_WIDTH, pad=False), 1))

    # Footer text if we have it
    if FOOTER_TEXT:
        console.print(Padding(_make_rich_rext(FOOTER_TEXT, STYLE_FOOTER_TEXT), (1, 1, 0, 1)))

    from rich.terminal_theme import DIMMED_MONOKAI
    console.save_svg(
        "/Users/APCamargo-M55/Documents/genomad/help_dialog.svg",
        title="genomad",
        theme=DIMMED_MONOKAI,
        code_format=CONSOLE_SVG_FORMAT,
        )
```

**Comment by apcamargo** [comment] 2022-05-16 21:40
@willmcgugan Just as a sanity check, I looked at another documentation that uses rich's SVG and it also looks broken in Firefox:

![image](https://user-images.githubusercontent.com/22940964/168686901-68723515-6641-4654-95c1-36e8969e89c7.png)

Unfortunately, I don't know a thing about SVGs and I don't know if there's a way of generating a Firefox-safe file.

**Comment by apcamargo** [comment] 2022-05-17 18:53
Thanks, @willmcgugan! I'll give it a try

**Comment by apcamargo** [comment] 2022-05-17 20:28
It is now generating empty SVGs:

![image](https://user-images.githubusercontent.com/22940964/168904173-e58373dc-6ffe-48f1-b443-5a5e0d10abd7.png)

**Comment by willmcgugan** [comment] 2022-05-18 08:17
Works for me in Firefox. Can you send me your SVG?

![debug](https://user-images.githubusercontent.com/554369/168991348-9d2ff486-37a7-470a-8faf-45723415a53e.svg)
<img width="1348" alt="Screenshot 2022-05-18 at 09 13 52" src="https://user-images.githubusercontent.com/554369/168991388-29e8cc69-d98d-45c4-9d48-84c39083938f.png">

**Comment by apcamargo** [comment] 2022-05-23 16:20
I'm really sorry. I've been swamped I couldn't find the time to run another test.

Thanks for the new release!

**Comment by willmcgugan** [comment] 2022-06-10 10:33
Closing because the SVG export has changed, and I can't reproduce the issue.

**Closed by willmcgugan** 2022-06-10 10:33 UTC
Labels: Needs triage
