### ISSUE TITLE
[BUG] Status spinner not working with webbrowser

### ISSUE THREAD

**Issue by Alwinator** [Textualize/rich#2517] opened 2022-09-09 09:20 UTC
**Describe the bug**

When using rich with the in-build webbrowser package the spinner shows weird symbols. Every second the spinner looks correct, but every other second it looks wrong. Maybe this is caused by the memory/CPU increase when starting the browser windows.

**Reproduction code:**
```python
import webbrowser
from rich.status import Status

with Status("Opening browser windows"):
    for _ in range(5):
        webbrowser.open_new_tab("https://google.com")
```

**Expected result:**
![image](https://user-images.githubusercontent.com/39517491/189315247-c4dca4db-bd5c-4e86-bdac-19021d3e6ef9.png)

**Actual result:**
![189314674-1341a7ff-f227-444b-9e44-57e43a349754](https://user-images.githubusercontent.com/39517491/189315569-abd5fb99-3157-43fd-8644-41caac80f963.png)

**Platform**
<details>
<summary>Click to expand</summary>

Platform: Windows 10 Enterprise, 64 Bit, **however**, I am using WSL2, so it runs on Ubuntu 20.04
Browser / Default Browser: Microsoft Edge
Terminal: [Windows Terminal](https://www.microsoft.com/store/productId/9N0DX20HK701) Version: 1.14.2281.0

I may ask you to copy and paste the output of the following commands. It may save some time if you do it now.

If you're using Rich in a terminal:

```
python -m rich.diagnose
pip freeze | grep rich
╭───────────────────────── <class 'rich.console.Console'> ─────────────────────────╮
│ A high level console interface.                                                  │
│                                                                                  │
│ ╭──────────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=120 ColorSystem.EIGHT_BIT>                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                  │
│     color_system = '256'                                                         │
│         encoding = 'utf-8'                                                       │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> │
│           height = 30                                                            │
│    is_alt_screen = False                                                         │
│ is_dumb_terminal = False                                                         │
│   is_interactive = True                                                          │
│       is_jupyter = False                                                         │
│      is_terminal = True                                                          │
│   legacy_windows = False                                                         │
│         no_color = False                                                         │
│          options = ConsoleOptions(                                               │
│                        size=ConsoleDimensions(width=120, height=30),             │
│                        legacy_windows=False,                                     │
│                        min_width=1,                                              │
│                        max_width=120,                                            │
│                        is_terminal=True,                                         │
│                        encoding='utf-8',                                         │
│                        max_height=30,                                            │
│                        justify=None,                                             │
│                        overflow=None,                                            │
│                        no_wrap=False,                                            │
│                        highlight=None,                                           │
│                        markup=None,                                              │
│                        height=None                                               │
│                    )                                                             │
│            quiet = False                                                         │
│           record = False                                                         │
│         safe_box = True                                                          │
│             size = ConsoleDimensions(width=120, height=30)                       │
│        soft_wrap = False                                                         │
│           stderr = False                                                         │
│            style = None                                                          │
│         tab_size = 8                                                             │
│            width = 120                                                           │
╰──────────────────────────────────────────────────────────────────────────────────╯
╭─── <class 'rich._windows.WindowsConsoleFeatures'> ────╮
│ Windows features available.                           │
│                                                       │
│ ╭───────────────────────────────────────────────────╮ │
│ │ WindowsConsoleFeatures(vt=False, truecolor=False) │ │
│ ╰───────────────────────────────────────────────────╯ │
│                                                       │
│ truecolor = False                                     │
│        vt = False                                     │
╰───────────────────────────────────────────────────────╯
╭────── Environment Variables ───────╮
│ {                                  │
│     'TERM': 'xterm-256color',      │
│     'COLORTERM': None,             │
│     'CLICOLOR': None,              │
│     'NO_COLOR': None,              │
│     'TERM_PROGRAM': None,          │
│     'COLUMNS': None,               │
│     'LINES': None,                 │
│     'JUPYTER_COLUMNS': None,       │
│     'JUPYTER_LINES': None,         │
│     'JPY_PARENT_PID': None,        │
│     'VSCODE_VERBOSE_LOGGING': None │
│ }                                  │
╰────────────────────────────────────╯
platform="Linux"
rich==12.5.1
```

**Comment by willmcgugan** [comment] 2022-09-09 09:25
Does it occur if you replace webbrowser with time.sleep(1)?

**Comment by Alwinator** [comment] 2022-09-09 09:28
> Does it occur if you replace webbrowser with time.sleep(1)?

No, with time.sleep it works fine.

**Comment by willmcgugan** [comment] 2022-09-09 09:35
Bizarre. We will investigate, but I suspect a bug in Windows Terminal at this point.

**Comment by darrenburns** [comment] 2022-09-22 15:46
I wonder if the terminal is interpreting the spinner bytes in some encoding other than utf-8.

I haven't been able to reproduce it on Windows Terminal (albeit not on WSL).

**Comment by Alwinator** [comment] 2022-09-23 06:44
Maybe there is a connection between CPU utilization and the bug. You can try to run the code on a slow computer or run a benchmark in the background where all your cores are utilized. 

I also tried it with other terminals. I have the same bug with PowerShell, CMD, and the native WSL terminal. (The code always ran in WSL). Please try it in WSL, I think that could be the trigger of the bug.

**Comment by Alwinator** [comment] 2022-10-27 12:16
@willmcgugan @darrenburns Is there any news regarding this issue? Were you able to reproduce the bug? Do you need more information?

**Comment by willmcgugan** [comment] 2022-10-27 12:53
We haven't managed to reproduce it. Suspect it isn't a Rich bug per se. More likely environmental, but it would be nice to know the root cause.

**Comment by Alwinator** [comment] 2022-10-28 08:47
@willmcgugan If you need more information, to investigate or to reproduce the bug, I am happy to help! :)

**Comment by willmcgugan** [comment] 2022-11-07 10:46
Sorry, we can't reproduce this at all. Let us know if you figure anything more out.

Closing for now, but more than happy to look at it again if we have something more to go on.

**Closed by willmcgugan** 2022-11-07 10:46 UTC
Labels: Needs triage
