### ISSUE TITLE
[REQUEST] Add support for ending a section without having to print a blank row

### ISSUE THREAD

**Issue by tonycombocurve** [Textualize/rich#2507] opened 2022-09-02 16:43 UTC
I have a long table and it makes sense to use sections to logically divide sets of rows. Because the adding of rows happens within a loop, I don't know if I am on the last row of a section without having to change the way I iterate. So what I did for now is print an empty row and pass end_section=True as follows:

```
table.add_row(end_section=True)
```

This is what it looks like:

![image](https://user-images.githubusercontent.com/103965224/188199584-def9af15-c1b3-4c58-a268-ea9490a89ac3.png)

It would be very useful to be able to end a section without having to print a blank row. That way we could achieve something like this:

![image](https://user-images.githubusercontent.com/103965224/188200037-500fba1a-c5db-491e-a1a7-4eb45fb82801.png)

Please let me know if you need any additional info. Thanks in advance for considering this feature request.

**Comment by willmcgugan** [comment] 2022-09-02 20:02
dupe of https://github.com/Textualize/rich/issues/2478

In the meantime, you could use this:

```python
from typing import Iterable, Tuple, TypeVar

T = TypeVar("T")

def loop_last(values: Iterable[T]) -> Iterable[Tuple[bool, T]]:
    """Iterate and generate a tuple with a flag for last value."""
    iter_values = iter(values)
    try:
        previous_value = next(iter_values)
    except StopIteration:
        return
    for value in iter_values:
        yield False, previous_value
        previous_value = value
    yield True, previous_value
```

**Closed by willmcgugan** 2022-09-02 20:02 UTC
Labels: Needs triage
