### ISSUE TITLE
Progress Bar Help

### ISSUE THREAD

**Issue by Swayam25** [Textualize/rich#2789] opened 2023-01-31 11:08 UTC
![image](https://user-images.githubusercontent.com/108215141/215743095-77c78828-94e7-41b8-afeb-4a2b330167fb.png)

While downloading a video via [`pytube`](https://github.com/pytube/pytube/) after completion of one progress bar the same repeats 2 -3 times or even more. After downloading 1 video the terminal becomes mess.

## Code
```py
        #progress bar
        progress = Progress(
            TextColumn("[progress.percentage]{task.percentage:>3.0f}%"),
            BarColumn(),
            DownloadColumn(),
            TextColumn("|"),
            TimeElapsedColumn()
        )
        
        #downloading
        for id in music_ids:
            task = None
            with progress:
                #progress task
                video = YouTube(f"https://youtube.com/watch?v={id}")
                progress.console.print(f"\n🔄 [green]Downloading[/] [bold cyan]{video.title}[/]")
                task = progress.add_task(description="Downloading", total=video.streams.filter(only_audio=self.only_audio).first().filesize)
                #youtube
                video = YouTube(f"https://youtube.com/watch?v={id}", on_progress_callback = lambda stream, chunk, bytes_remaining: progress.advance(task, advance=stream.filesize - bytes_remaining))
                music_name = video.title
                #error check
                if os.path.exists(f"./{playlist_name}/{video.title}.mp3" if self.only_audio else f"./{playlist_name}/{video.title}.mp4"):
                    continue
                else:
                    #download
                    video.streams.filter(only_audio=self.only_audio).first().download(output_path=f"./{playlist_name}", filename=f"{video.title}.mp3" if self.only_audio else f"{video.title}.mp4")
        if playlist_name:
            console.print(f"\n🎉 [green]Successfully Downloaded[/] [bold cyan]{playlist_name}[/] - [green]{len(music_ids)} songs[/]\n")
            console.print(music_skipped)
        else:
            console.print(f"\n🎉 [green]Successfully Downloaded[/] [bold cyan]{music_name}[/] - [green]{datetime.timedelta(seconds=video.length)}[/]\n")
```

**Comment by willmcgugan** [comment] 2023-01-31 11:41
I'm afraid I can't help you debug your code. Suggest you reduce the example to a small fully-working snippet, i.e. something I can cut and paste. That will help us identify the problem.

It would also help if you make an attempt to fill out the issue template.

**Comment by Swayam25** [comment] 2023-02-01 06:44
> I'm afraid I can't help you debug your code. Suggest you reduce the example to a small fully-working snippet, i.e. something I can cut and paste. That will help us identify the problem.
> 
> It would also help if you make an attempt to fill out the issue template.

```py
import os
import json
import datetime, time
import requests
import rich
import pytube
from pytube import YouTube, Playlist, Search
from rich.console import Console
from rich.panel import Panel
from rich.progress import Progress, BarColumn, TextColumn, TimeElapsedColumn, DownloadColumn

#rich
console = Console()

class MediaDownloader():
    def __init__(self, query, only_audio = True):
        self.query = query
        self.only_audio = only_audio

    #download
    def download(self):
        music_ids = []
        music_name = ""
        music_skipped = ""
        playlist_name = ""
        #youtube
        if "youtu" in self.query:
            if self.query.startswith("https://www.youtube.com/playlist"):
                playlist = Playlist(self.query)
                playlist_name = playlist.title
                for url in playlist.video_urls:
                    music_ids.append(url.split("=")[1])
            elif self.query.startswith("https://www.youtube.com/watch"):
                music_ids.append(self.query.split("=")[1])
            elif self.query.startswith("https://youtu.be/"):
                music_ids.append(self.query.split("/")[3])
        #search
        else:
            try:
                search = Search(self.query)
                music_ids.append(search.results[0].video_id)
            except Exception:
                console.print("\n❌ [red]No results found![/]\n")
                exit()

        #progress bar
        progress = Progress(
            TextColumn("[progress.percentage]{task.percentage:>3.0f}%"),
            BarColumn(),
            DownloadColumn(),
            TextColumn("|"),
            TimeElapsedColumn()
        )
        
        #downloading
        for id in music_ids:
            task = None
            with progress:
                #progress task
                video = YouTube(f"https://youtube.com/watch?v={id}")
                progress.console.print(f"\n🔄 [green]Downloading[/] [bold cyan]{video.title}[/]")
                task = progress.add_task(description="Downloading", total=video.streams.filter(only_audio=self.only_audio).first().filesize)
                #youtube
                video = YouTube(f"https://youtube.com/watch?v={id}", on_progress_callback = lambda stream, chunk, bytes_remaining: progress.advance(task, advance=stream.filesize - bytes_remaining))
                music_name = video.title
                #error check
                if os.path.exists(f"./{playlist_name}/{video.title}.mp3" if self.only_audio else f"./{playlist_name}/{video.title}.mp4"):
                    continue
                else:
                    #download
                    video.streams.filter(only_audio=self.only_audio).first().download(output_path=f"./{playlist_name}")
        if playlist_name:
            console.print(f"\n🎉 [green]Successfully Downloaded[/] [bold cyan]{playlist_name}[/] - [green]{len(music_ids)} songs[/]\n")
            console.print(music_skipped)
        else:
            console.print(f"\n🎉 [green]Successfully Downloaded[/] [bold cyan]{music_name}[/] - [green]{datetime.timedelta(seconds=video.length)}[/]\n")

#inputs
panel = Panel.fit(
                  "🔻 [bold cyan]Supports [red]YouTube[/] & [green]Spotify[/]! Provide music name, playlist, link etc to work! Supports both video & audio![/] 🔻", 
                  box=rich.box.DOUBLE,
                  title="🌟 [bold green]Media Downloader[/] 🌟",
                  border_style="cyan",
                  padding=(1, 4)
                 )
console.print(panel)
query = console.input("\n[cyan]Enter the name, playlist or link want to download[/]: ")
only_audio = console.input("[cyan]Do you want to download only audio?[/] [green]Y[/] / [red]N[/]: ").lower()
if query == "":
    console.print(f"\n❌ [bold red]Nothing was there to download[/]\n")
else:
    MediaDownloader(query=query, only_audio=True if only_audio == "y" else False).download()
```

**Comment by willmcgugan** [comment] 2023-03-04 16:35
I need a minimal working example that narrows down the issue. Which means you need to exclude all dependancies, and code unrelated to the bug. That will help us know where the issue is. As it stands, the most likely explanation is that the bug is in your code, and not Rich.

Closing. But feel free to open a new issue, and please fill in the issue template this time.

**Closed by willmcgugan** 2023-03-04 16:35 UTC
Labels: Needs triage
